### ISSUE TITLE
form not rendered

### ISSUE THREAD

**Issue by mickaelmarin** [mishbahr/djangocms-forms#11]
Hi,

I have django cms 3.1.2 with django 1.8.3 installed.
I followed your installation instructions all work fine and I haven't any errors.

I can assign form app to a page, hook form on placeholder, edit the form and save it but the form is not rendered. When I inspect the DOM with chrome I only view the DIV container for the plugin and nothing inside this.

Any idea ?

thanks

**Comment by mishbahr** [comment]
It's a CMS bug. 
Same as this https://github.com/stefanfoulis/cmsplugin-filer/issues/190
And according to @yakky 
https://github.com/stefanfoulis/cmsplugin-filer/issues/190#issuecomment-123864943. 
Fix is coming for 3.1.3

**Comment by mishbahr** [comment]
This has been fixed in django-cms 3.1.3.

Tested with ``djang==1.8.4`` and ``django-cms==3.1.3``
