### ISSUE TITLE
Field names with spaces causes export to miss data

### ISSUE THREAD

**Issue by jsoa** [mishbahr/djangocms-forms#12]
Having a field name with spaces results in the following option in the export admin page
```jinja
<select id="id_headers_to" multiple="multiple" size="0" name="headers" class="filtered" style="height: 262px;">
 <option value="Favorite">Favorite JS Framework</option>
</select>
```

Then exporting the data for this field is always `None`

**Comment by mishbahr** [comment]
Thanks for reporting this issue. I was able to replicate the issue. 

I'll look into it as soon as possible. 

— Mishbah

**Comment by mishbahr** [comment]
@jsoa Haven't published this to pypi just yet (I'll do it tonight). Please let me know if the fix works! Thanks
— Mishbah

**Comment by jsoa** [comment]
@mishbahr thx, ill check it out

**Comment by jsoa** [comment]
:+1: thx for the quick fix

**Comment by mishbahr** [comment]
Don't forget to "star" the repo.. 😊
