### ISSUE TITLE
Can't use filefield with S3 storage backend

### ISSUE THREAD

**Issue by driesdesmet** [mishbahr/djangocms-forms#14]
Using this setting:

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

I'm getting

    NotImplementedError at /forms/submit/
    This backend doesn't support absolute paths.

I wonder if it's really necessary to return the filepath in the handle_uploaded_files() function, since a StoredUploadedFile field is save in form.cleaned_data for later sending and saving.

**Comment by mishbahr** [comment]
From what I can remember — I needed the files later to be be used as an attachment for sending email submissions via email. See: https://github.com/mishbahr/djangocms-forms/blob/master/djangocms_forms/forms.py#L357

**Comment by driesdesmet** [comment]
You seem to approach the uploaded files from the fields, while when using a FormView as you do, the files are available in form.files already. Any reason why you took this approach?
I'd like to rewrite it a bit, but don't want to overlook something.

**Comment by mishbahr** [comment]
I'm more than happy for you to refactor bits.
Just looking through the code.. can't really remember why I did it this way.

**Comment by mishbahr** [comment]
I slightly refactored the email attachment logic last night. Now we get the files form `request.FILES` . Please try this, and let me know.

— Mishbah

**Comment by driesdesmet** [comment]
Hi mishbahr. Thank you for your work. I was doing the same this morning, and since I'm trying to improve on my programming skill, I would care if you have a look at it. I've made a pull new PR15, but it doesn't automerge with the changes you've done.

I think my patch particularly solves my problem I had with an S3 storage class which doesn't provide a .path method. So in my case, your solution wouldn't work. I'm going to comment on your code to open up discussion. Again, I'm not an experienced contributor, but I'd like to very much improve. Let me know what you think.

**Comment by mishbahr** [comment]
Hmm. looks like we both did very similar thing. I removed the bit where I was trying to access the file path.. and as for attachments.. I'm looping through `request.FILES` instead of `form.files` as per doc here: https://docs.djangoproject.com/en/1.8/topics/http/file-uploads/#basic-file-uploads 

Please try using my latest commit and see if it works with S3 Storage. If not .. I'll try to resolve the merge conflict. Thanks

**Comment by mishbahr** [comment]
UPDATE:  I have just tried my code using django-storages-redux==1.3 with:

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

Its uploads to S3 bucket just fine. However the email attachment seems to `0 Bytes` :-(

**Comment by driesdesmet** [comment]
Yes. I fixed this. One moment.

On 7 October 2015 at 15:49, Mishbah Razzaque <notifications@github.com>
wrote:

> UPDATE: I have just tried my code using django-storages-redux==1.3 with:
>
> DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
>
> Its uploads to S3 bucket just fine. However the email attachment seems to 0
> Bytes :-(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mishbahr/djangocms-forms/issues/14#issuecomment-146201217>
> .
>



-- 
Dries Desmet



*URGA | creatieve communicatie*

Zuiderlaan 69
8790 Waregem
t 056 61 41 94
m 0477 19 41 13
dries@urga.be
www.urga.be

**Comment by driesdesmet** [comment]
It's because Django's file object returns an empty bytestring when the file object is not open yet. I'm not sure if this is expected behaviour. It should probably return an exception rather than just a zero length bytestring. the #16 PR runs for me now.

**Comment by driesdesmet** [comment]
btw, I wondered why you create a hash for file names at all. Is that because they wouldn't get overwritten? Doesn't Django create a new filename anyway if it already exists? I also noticed that you generate a has only once for every file field, which means filenames uploaded within the same form would have the same hash. Intended?

**Comment by mishbahr** [comment]
Just committed fully working code :-)

As far as using a hash in filename -- its not based on filename but rather just a UUID appended to filename. So I'm hoping it will be unique per file.

**Comment by driesdesmet** [comment]
If you'd like it to be unique per file, you should probably put it within the for loop for every file field in handle_uploaded_files. No?

**Comment by driesdesmet** [comment]
btw, I've sent you a google chat invitation. Thought that would talk easier. Couldn't see your name in django-cms chatroom either. My nichname is TrioTorus.

**Comment by mishbahr** [comment]
You are correct! 

Fixed in 88dda1fea8f61c61686e40058f58307ab58d0d31

Thanks

**Comment by driesdesmet** [comment]
Happy to help. I'm delighted you made this plugin, and now it works with S3!

On 7 October 2015 at 16:21, Mishbah Razzaque <notifications@github.com>
wrote:

> You are correct!
>
> Fixed in 88dda1f
> <https://github.com/mishbahr/djangocms-forms/commit/88dda1fea8f61c61686e40058f58307ab58d0d31>
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mishbahr/djangocms-forms/issues/14#issuecomment-146209146>
> .
>



-- 
Dries Desmet



*URGA | creatieve communicatie*

Zuiderlaan 69
8790 Waregem
t 056 61 41 94
m 0477 19 41 13
dries@urga.be
www.urga.be

**Comment by mishbahr** [comment]
I'll push it to PyPi :-)
