### ISSUE TITLE
Exporting to excel throws 500 when form name is > 31 chars

### ISSUE THREAD

**Issue by jsoa** [mishbahr/djangocms-forms#17]
Line in question: https://github.com/mishbahr/djangocms-forms/blob/master/djangocms_forms/admin.py#L165

```python
dataset = Dataset(title=latest_submission.plugin.name)
```

Limitation on excel sheet names cause exporting data that contain names greater then 31 characters. Here is the line that checks for sheet names in `xlwt`  lib https://github.com/kennethreitz/tablib/blob/a785d77901f307ef499621753b078743e2fabb81/tablib/packages/xlwt/Utils.py#L185 and the line that raises the exception https://github.com/kennethreitz/tablib/blob/a785d77901f307ef499621753b078743e2fabb81/tablib/packages/xlwt/Workbook.py#L318-L319

Not sure the best solution, perhaps `title[:31]` when making the dataset or enforcing the name to have a max length.

**Comment by mishbahr** [comment]
Thanks for raising this issue. I was able to reproduce it. I'll push a fix tonight.
