### ISSUE TITLE
Installing djangocms-forms in Aldryn environment makes adding plugins fail

### ISSUE THREAD

**Issue by Kurdym** [mishbahr/djangocms-forms#19]
I setup a new site in Aldryn, just by using their dashboard to collect addons I want.
Thereby I uninstall their default Aldryn-Forms and install Django-cms-forms.

Then I deploy the test site and try to add any plugin, i.e. "text" or "form".

The page fails to add the plugin, and comes back with an error.

Sometimes it seems it did add the plugin, only showing after I surf away, and back to the page again.

Unfortunately I don't have any logs, since they only flash by at the Aldryn environment.

**Comment by mishbahr** [comment]
Both aldryn forms plugin and this plugin uses plugin name `FormPlugin`.. it could be the that there is registry error.

Unfortunately I can't help you to resolve this issue, please contact Aldryn support for help.

Thanks

Mishbah
