### ISSUE TITLE
UnicodeEncodeError at /ru/

### ISSUE THREAD

**Issue by rt-em** [mishbahr/djangocms-forms#21]
Hello, Mishbahr!
I'm getting error when using cyrillic letters for options in dropdown list or radio buttons.

`UnicodeEncodeError at /ru/
'ascii' codec can't encode characters in position 2-8: ordinal not in range(128)`

Could you add support of the unicode for dropdowns and other controls in your form app?

**Comment by mishbahr** [comment]
Ooops! Thank you for reposting this issue. 

How can I fix this (pull requests are welcome)? 

Should I add the following to each file?

    # -*- coding: utf-8 -*-
    from __future__ import unicode_literals

Regards,
— Mishbah

**Comment by rt-em** [comment]
I never used git before:) Only just for cloning repos. I think I need to learn how to use it before pull the code for revision. But I can help you translate the plugin to Russian in transifex.

From my experience it works in most cases if you add this to .py files
`# -*- coding: utf-8 -*- `
`from __future__ import unicode_literals `

Best regards,
Artem

**Comment by mishbahr** [comment]
I'll be more than happy to add `from __future__ import unicode_literals` to all files.

Please allow few days.. I'm insanely  busy right now.

Thanks

Mishbah

**Comment by mishbahr** [comment]
hey @rt-em I have added `from __future__ import unicode_literals ` to all `.py` files.

See f6fc6da25ed43f4cfb918c5eb4ad89c331ff1e54

Can you please pip install from github and see if that solves your problem.

Thanks,

— Mishbah

**Comment by rt-em** [comment]
Hi, @mishbahr

I tried to install the latest version of djangocms-forms, but had the same problem. I checked the traceback, and found that the problem in line 211 of models.py:
`return [(str(choice), str(choice)) for choice in choices]`
Then I found models.py in site-packages and replaced the line with:
`return [(unicode(choice), unicode(choice)) for choice in choices]`

I don't know is it correct way of revision, but now everything works perfectly

Best regards,
Artem

**Comment by mishbahr** [comment]
I haven't forgotten about this. Last few days been very busy.. I'll push a fix as soon as I can.

Thanks

**Comment by mishbahr** [comment]
Fixed with commit e7f2aeb24152c5e10e4392ab55f6485e7a768fb2
