### ISSUE TITLE
Error in "Export Form submissions"

### ISSUE THREAD

**Issue by Monicajramos** [mishbahr/djangocms-forms#22]
Hi Mishbahr!

Thank you for sharing you djangocms-forms.
I was getting an error when trying to "Export Form submissions" in Home › Forms › Form submissions. 
I want to share with you what I did to solve it, in case I can help someone else: 

Exception Value:  'WSGIRequest' object has no attribute 'REQUEST'
Exception Location:	/home/VirtualEnvs/project/lib/python3.5/site-packages/djangocms_forms/admin.py in export_view, line 242

What I did was replace (in admin.py) the line242---> 'is_popup': '_popup' in request.REQUEST,
by--->  'is_popup': request.GET.get('_popup'),

Thank you and best regargs!

**Comment by mishbahr** [comment]
Thanks for reporting this. I'll update the code asap.

Regards

Mishbah
