### ISSUE TITLE
No green plus icon at the bottom of the form creation popup

### ISSUE THREAD

**Issue by jesusjl** [mishbahr/djangocms-forms#23]
I cannot add fields using django==1.6.11  , djangocms-forms==0.1.16 and django-cms==3.1.5 in a vanilla cms project.

Notice javascript  error..	
inlines.js 

TypeError: $(...).prop is not a function

**Comment by mishbahr** [comment]
Thank you for reporting this. I'll look into this as soon as I can.

Unfortunately, I really busy right now .. this may take few weeks.

**Comment by mishbahr** [comment]
I wasn't able to reproduce the JS error..however there is a styling issue w/ the inline  "+ Add another Field" button. See attached screenshot.

<img width="1100" src="https://cloud.githubusercontent.com/assets/1264089/14548129/0a3f8df6-02ac-11e6-8b5a-bb22b0c3dc02.png">

I'll fix this as soon as I can. Many thanks.

**Comment by jesusjl** [comment]
Thank you mishbahr, i will give a try for then.
