### ISSUE TITLE
python34 Install on windows error!

### ISSUE THREAD

**Issue by pamxy** [mishbahr/djangocms-forms#24]
Traceback <most recent call last>:
  File "setup.py", line 23, in <module>
     readme = open('README.rst').read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x94 in position 4932: illegal multibyte sequence

and I found the problem in README.rst file on line 140 ~ line 144, the "—" symbol,change it to "-" and then will run success!

**Comment by mishbahr** [comment]
Hey @pamxy, thanks for reporting this. I'll push the fix as soon as I can.

Many thanks

Mishbah

**Comment by mishbahr** [comment]
Hey @pamxy Ive updated the README, please let me know if the issue is resolved.
