### ISSUE TITLE
Custom name attributes

### ISSUE THREAD

**Issue by lmanzurv** [mishbahr/djangocms-forms#25]
Currently, the name attribute of a field is defined from the field name. This means that if I have the same form in different languages, there's no way of mapping the fields between languages. Is there a way to define a custom name attribute value for each field?

**Comment by mishbahr** [comment]
Hi @lmanzurv, sorry for a late response. 

What to you mean by same form but different language? 2 identical forms in the same page but in different language, that are displayed at the same time? And what to mean by mapping? Is this for some custom javascript? Please can you give an example?

**Comment by lmanzurv** [comment]
Sorry if I wasn't clear. I have 1 page that exists in 5 different languages. Each of the languages has one form (in the corresponding language). All the forms are the same. When the form is submitted, I execute a function that is triggered by the form_submission signal you send. I have to obtain all the values and send them to an external system. But the values come with different field names (i.e. in english I get field 'name' but in spanish I get field 'nombre'). This happens because the fields' names are set from the label that is specified on the form creation.

I suggest adding a property for a field where we can define the value that the HTML attribute name is going to have. That way I can define the same name for the fields that are "a match" between languages, thus avoiding having to make workarounds to "map" them on the signal-triggered function.

Right now, what I do, is pass an object on the description with different properties, one of which is the name attribute, and on the template, I process the object and set the values accordingly. That way, on the signal I process the fields received and instantiate a FormBuilder object to rename the fields with the information of the name set by the form and the name received on the object (specified on the description).

Don't know if I was clear, and can include code snippets if you wish.

**Comment by mishbahr** [comment]
Wow. That's a lot of workaround for something that could be solved by adding an extra field. I'll update the package this weekend to include optional 'field_name' field.

**Comment by lmanzurv** [comment]
Yes. I know, but unfortunately I didn't have the time to make the changes myself because I needed the solution ASAP. 

I was actually thinking that there could be a dict-like field to include HTML attributes (like data-attributes) instead of just a field for the name. I could make that myself and send a pull request.

---------------------------------------
Laura Cristina Manzur Villalobos, M.Sc
Ingeniera de Sistemas y Computación
Cel.: [57] 3013382150
Bogotá, Colombia

**Comment by mishbahr** [comment]
Hey @lmanzurv, Please add `DJANGOCMS_FORMS_ALLOW_CUSTOM_FIELD_NAME=True` to your `settings.py`.

This will add extra field to the form field inlines, see screenshot below.

<img width="709" alt="" src="https://cloud.githubusercontent.com/assets/1264089/15803084/665503ec-2ac4-11e6-8c76-7e1237316f3d.png">

If you find any issue, please feel free to reopen this issue.

Otherwise, leave me 👍 and I'll do a new release to PyPi.

Don't forget to 🌟 this repo 😛 

Many Thanks

**Comment by lmanzurv** [comment]
It is perfect. Thank you very much!

**Comment by lmanzurv** [comment]
Hi, is the modification already up in PyPi? I checked and still see version 0.1.17

**Comment by mishbahr** [comment]
Sorry haven't had a chance to do that :-( .. I'll do it as soon as I can!

**Comment by lmanzurv** [comment]
No problem. Please let me know as soon as you do so I can update my project ;)

**Comment by mishbahr** [comment]
Done! https://pypi.python.org/pypi/djangocms-forms/0.2
