### ISSUE TITLE
invalid "This field is required" error after submit

### ISSUE THREAD

**Issue by herzaso** [mishbahr/djangocms-forms#26]
I have a form with two fields - email (type Email) and message body (type Text Area).
Both fields are required, but after I fill them and Submit the form (form is indeed submitted), I get the above error from /forms/submit ({"errors": {"__all__": ["This field is required."]}, "formIsValid": false})

**Comment by mishbahr** [comment]
I was unable to reproduce this issue using:

* django (1.8.13)
* django-cms (3.3.0)
* djangocms-forms (0.1.17)

See screenshots:

1. Initial form w/ 2 fields.
![Contact Form](https://cloud.githubusercontent.com/assets/1264089/15680397/83c4ef84-274d-11e6-956f-c4c01bf3ff6d.png)

2. "Thank You" message after successful form submission.
![Thank You Message](https://cloud.githubusercontent.com/assets/1264089/15680400/86a20dd6-274d-11e6-8fcd-4005795e0417.png)
 
3. Submitted message in `/admin`
![Form Submission](https://cloud.githubusercontent.com/assets/1264089/15680560/10955bba-274e-11e6-9711-48e092632340.png)

**Comment by herzaso** [comment]
I think I know what the problem was – I was using a void name for the fields (single space character) since I didn’t want to see the label and couldn’t find how to remove it.

I ended up using a “display:none” css on the label since that wasn’t enough (also has the asterisk issue).

 

After restoring the names I now get a “something unexpected happened” exception but looking at the response I see SMTPServerDisconnected so I guess it’s something here.

 

Is there any way to remove the label and required indication? For the required character I think you need to add it with a css (“:after”) – that way, it would be removable. For the label, if there is no way to remove it, you might want to consider adding a way (nowadays, using placeholders instead of labels is common practice…)

**Comment by mishbahr** [comment]
Just override this template: /templates/djangocms_forms/form_template/default.html
Or you can have multiple templates, by overriding template setting:

     DJANGOCMS_FORMS_TEMPLATES = (
        ('djangocms_forms/form_template/default.html', _('Default')),
        ('path/to/your/template/your_template.html', _('Your template')),
    )
 and the editor can choose between using the default or your own custom template.

**Comment by herzaso** [comment]
This works but the URL is always redirected after submission (I’ve attached my form template).

Django 1.8.12

django-cms 3.2.5

djangocms-forms 0.1.17

 

Same form with the default template works as expected …

**Comment by mishbahr** [comment]
Thats expected behaviour. Please read the README.

**Comment by herzaso** [comment]
I have read it several times.

It doesn’t say (or at least, I couldn’t find it) that by using a custom template the page will always be redirected.

Let me reiterate that the page is not redirected when using the default template (ajax is used) and it is redirected when using a custom template (form action is used instead of ajax)

**Comment by mishbahr** [comment]
In you custom template have you included the javascript required to use ajax submission?

**Comment by herzaso** [comment]
I have, but I now realize that the form must be inside a class named “forms” (the outer most div).

In my template, I have changed it to class=“form” and that’s why it didn’t work…

 

Sorry for the trouble. I should try next time not to change too many things at once …

**Comment by mishbahr** [comment]
No worries... happy to help. Glad to hear you've managed to resolve your issues. 
Don't forget to :star: this repo 😛

**Comment by herzaso** [comment]
Is there any way to control individual inputs?
I want to add some "aria" properties to each input (e.g. <input aria-labelledby="foo bar">

**Comment by mishbahr** [comment]
Please have a look at https://pypi.python.org/pypi/django-widget-tweaks
