### ISSUE TITLE
404 Using Postgres DB

### ISSUE THREAD

**Issue by viper8690** [mishbahr/djangocms-forms#28]
I was able to successfully create a simple form using sqlite3 db. I switched to a Postgres db, ran `python manage.py migrate` with no problems and tried the same code and I come up with a 404 error.

`Page not found (404)`
`Request Method:	POST`
`Request URL:	http://127.0.0.1:8000/en/forms/submit/`
`Raised by:	cms.views.details`
`Using the URLconf defined in jsg.urls, Django tried these URL patterns, in this order:`
`^media/(?P<path>.*)$`
`^static\/(?P<path>.*)$`
`^en/ ^admin/`
`^en/ ^sitemap\.xml$`
`^en/ ^select2/`
`^en/ ^ ^cms_wizard/`
`^en/ ^ ^(?P<slug>[0-9A-Za-z-_.//]+)/$ [name='pages-details-by-slug']`
`^en/ ^ ^$ [name='pages-root']`
`^en/ ^ ^forms/submit/$ [name='djangocms_forms_submissions']`
`The current URL, /en/forms/submit/, didn't match any of these.`

I went back to the original default template and it is still the same problem.

**Comment by mishbahr** [comment]
As I understand it, you swapped db backend from `sqlite` to `postgresql`. How did you include form submission page urls?

Did you add djangocms_forms.urls to your project's urls, like this:

    urlpatterns = patterns(
        url(r'^forms/', include('djangocms_forms.urls')),
    )

or create a django CMS page to hook the application into?

From the traceback above I suspect its the latter scenario .. for that you'll need to recreate the page and add `djangocms_forms` as an AppHook

**Comment by viper8690** [comment]
You're completely right that I didn't add the app hook. Thank you so much for your help and sorry for bothering you for such a silly mistake. Ramadan Kareem.

**Comment by mishbahr** [comment]
As I understand it.. you swapped db backends. How did you attach tthe

**Comment by mishbahr** [comment]
Don't forget to 🌟 this repo 😄
