### ISSUE TITLE
Class/Id attributes

### ISSUE THREAD

**Issue by mititicu** [mishbahr/djangocms-forms#3]
There's no option to manage in template classes or ids for fields?

**Comment by mishbahr** [comment]
Field input ID are auto generated based on field label and and as for adding additional classes to field input.. please have a look at https://pypi.python.org/pypi/django-widget-tweaks

I haven't implemented that allows you define classes for individual inputs. Let me know if django-widget-tweaks solves your issue..

**Comment by mishbahr** [comment]
A custom template tag that allows you to add additional css classes to a field.. should be really easy to implement.. I've added it to my list of improvements for djangocms-forms :-)

**Comment by mititicu** [comment]
I have fixed with template tag. Thank you!

**Comment by mishbahr** [comment]
@mititicu I updated `djangocms-forms` to allow custom classes for form `<input>`. 

See https://github.com/mishbahr/djangocms-forms/blob/master/djangocms_forms/conf.py#L67
and https://github.com/mishbahr/djangocms-forms/blob/master/djangocms_forms/models.py#L153
