### ISSUE TITLE
Pre-validations

### ISSUE THREAD

**Issue by lmanzurv** [mishbahr/djangocms-forms#30]
Hi,

Is there any way to add validations before the plugin's validations take place? I have a couple of fields that I initialize as not required, but if the user selects certain option, I have to make that field(s) required. Is there any way to achieve this with the current implementation of the plugin? If not, is there any way that I can prevent the plugin submit and do some validations of my own before triggering the plugin's submit?

**Comment by mishbahr** [comment]
Sorry IMO this is outside the scope of this plugin.
