### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by iainhouston** [mishbahr/djangocms-forms#34]
Underline symbol. Django CMS 3.4.1

    DJANGOCMS_FORMS_TEMPLATES = (
        ('djangocms_forms/form_template/default.html', _('Default')),
    )

should be: 

    DJANGOCMS_FORMS_TEMPLATES = (
        ('djangocms_forms/form_template/default.html', ('Default')),
    )

**Comment by mishbahr** [comment]
This not a typo... its wrapped to make template name translatable.

Please add `_ = lambda s: s`at the beginning of your settings file.
