### ISSUE TITLE
number field causes internal server error

### ISSUE THREAD

**Issue by iainhouston** [mishbahr/djangocms-forms#35]
Adding a number field to a form in `django-cms==3.4.1` with `djangocms-forms==0.2.1` using the `Default` form template causes `"POST /forms/submit/ HTTP/1.1" 500 18223` with `We're sorry. Something Unexpected Happened. Please Try Again Later.`.  

Whereas the same form before the number field had been added - a sole text field - successfully sent the form via email. Remove the number field and the form succeeds again.  

Change the number field to a checkbox or a phone number field and it all works fine too.

What can I do to determine what's going on?

**Comment by mishbahr** [comment]
Can you reproduce this locally? This normally happens if server returned a 500 error.

**Comment by iainhouston** [comment]
Yes, the above is what happens when running locally on django `manage.py runserver`  with `DEBUG = True`. Yes, the server returns a 500 error, as my OP. But there is not the usual debug screen so I can see no specific diagnostics.   

We are running on Python 3.5.2

**Comment by mishbahr** [comment]
What browser are you using?
If you are in `DEBUG` mode ..using Chrome dev tools, please have a look at the **Network** tab.
A full traceback for a 500 error should be available.

**Comment by vstoykov** [comment]
@iainhouston when you see the error do you have any traceback in the console (where the `manage.py runserver` is running)?

**Comment by iainhouston** [comment]
No Python traceback from `runserver ` but will look at browser network trace as soon as I can get back to this project from current schedule

**Comment by iainhouston** [comment]
Clean install of Django CMS.
Can't reproduce this issue now on Mac browsers: Safari 10.0.1; Firefox 47.0; Chrome 54.0.2840.98
Django==1.8.16; django-cms==3.4.1; Python 3.5.2

Thanks for looking at this. Apologies for false alarm!
