### ISSUE TITLE
basestring not defined in Python3

### ISSUE THREAD

**Issue by driesdesmet** [mishbahr/djangocms-forms#4]
The 'friendly' template filter has

```python
@register.filter
def friendly(value):
    if value in (None, '', [], (), {}):
        return None

    if type(value) is list:
        value = ', '.join(value)
    if type(value) is bool:
        value = yesno(value, u'{0},{1}'.format(_('Yes'), _('No')))
    if not isinstance(value, basestring):
        value = unicode(value)
    return value
```

but basestring is not defined when using python3. The default e-mail template is using this filter, so that's how I caught it. I'm not sure what the 'correct' solution is, because the whole python3 unicode thing scares me. Just thought I'd file this here.

**Comment by mishbahr** [comment]
Firstly, Thank You for taking the time to report the issue. I haven't had a change to test the package with python 3. 
As a quick fix, please try putting this on top of the templatetag file and let me if the error goes away.

    try:
        basestring
    except NameError:
       basestring = str

**Comment by mishbahr** [comment]
Pushed to PyPi :-)

https://pypi.python.org/pypi/djangocms-forms/0.1.5
