### ISSUE TITLE
Apphook support for CMS 3.4

### ISSUE THREAD

**Issue by marcosguedes** [mishbahr/djangocms-forms#41]
Django CMS 3.4 requires cms_app.py to be called cms_apps.py. `Form` can't be selected from the Application dropdown due to it (throwing a 404 on submit)

**Comment by mishbahr** [comment]
Thanks for reporting this.  I'll fix this.

**Comment by mishbahr** [comment]
Fixed! See 8addd368ad8900f5f72d13bf6b27bb4edd67aec7
