### ISSUE TITLE
Static Files Namespacing

### ISSUE THREAD

**Issue by rspeed** [mishbahr/djangocms-forms#43]
I consider this a low priority issue, but also one that can be easily fixed.

The standard practice for namespacing static files in django is to begin paths with a unique identifier, usually the package name. djangocms-forms instead uses "css/djangocms_forms" and "/djangocms_forms", which effectively creates two generic namespaces. This should be changed to reverse those path segments to "djangocms_forms/css" and "djangocms_forms/js".

**Comment by mishbahr** [comment]
This repo is based on https://github.com/pydanny/cookiecutter-djangopackage

I don't plan to change the structure of static files. Sorry.

Feel free to fork this repo. Thanks.
