### ISSUE TITLE
Feature Request - Create form once, use in several places

### ISSUE THREAD

**Issue by rolandf** [mishbahr/djangocms-forms#48]
Hi,
when adding a form to a placeholder, I'd like to be able to select an existing form from an inventory of all forms that have been created in addition to the possibility to create a new form.

Sample use case: Adding a subscribe to mailing list form in various places, with all data collected in the same form.

**Comment by mishbahr** [comment]
Have you considered using the "alias" plugin.  See https://youtu.be/QORHwLmdRyM

**Comment by mishbahr** [comment]
IMO this is out of scope for  djangocms-forms

**Comment by mishbahr** [comment]
@rolandf Sorry Im not being very helpful. Your request to "reuse" CMS plugins.. is genuinely out of scope for this project.  Let me know if using alias plugin or a static placeholder resolves your issue.

How often do you plan to reuse a plugin.. i.e is the mailing list subscription form one off requirement or is there lots of other cases where you need to reuse plugins?

Have a look at source code for alias plugin.. maybe you can modify that to match your needs?
Or can you just make a simple "subscribe to our mailing list" plugin.. with a hard coded form and django model to store the submissions.

**Comment by rolandf** [comment]
Hi @mishbahr I was completely unaware of the alias plugins which fit my need perfectly. Thank you very much!

**Comment by mishbahr** [comment]
:+1:
