### ISSUE TITLE
How to get CKEditor to handle Textarea?

### ISSUE THREAD

**Issue by Xosted** [mishbahr/djangocms-forms#54]
Hi,
I am sorry if this is not the right place to ask but I just couldn't figure out where to drop my question. I guess it must be simple but I couldn't find how to so CKEditor (already installed through djangocms-text-ckeditor) could be used to handled TextArea? Should I make a custom field? How?
Once again, sorry if it is not the right place and thank you for your help.

**Comment by mishbahr** [comment]
I'm sorry, but custom widgets are not supported by djangocms-forms.

**Comment by mishbahr** [comment]
Not sure how you would integrate `djangocms-text-ckeditor`, however it is possible to add additional classes to form inputs.
```python
DJANGOCMS_FORMS_WIDGET_CSS_CLASSES = {'textarea': ('ckeditor', ) }
```
The above setting will add `ckeditor` as CSS class to all "text area" inputs.

At this point, you can transform elements into a rich text editor by using the `.ckeditor()` method.

```js
$( 'textarea.editor' ).ckeditor();
```

See http://docs.ckeditor.com/#!/guide/dev_jquery

**Comment by mishbahr** [comment]
@Xosted hope the above comment helps. Let me know if you have any other questions.

**Comment by Xosted** [comment]
I will try this and will get back to you. Thanks a lot for your support.

**Comment by Xosted** [comment]
Hi, I manage to get the result that I wanted, using your suggestion. Thanks a lot!

**Comment by mishbahr** [comment]
👍
