### ISSUE TITLE
Change The template of Filed 

### ISSUE THREAD

**Issue by binydev** [mishbahr/djangocms-forms#56]
I want to change from this 
```python
{% if not field|is_checkbox %}
    {{ field}}
{% endif %}
```
to this 
```python
{% if not field|is_checkbox %}
    <input type="text" class="form-control" id="{{ field.auto_id }}" name="{{ field.name }}" placeholder="Name" required>
{% endif %}
```

but I can't know the property of the field, the only ting I know is .name and .auto_id 

by the way, it is customization of https://github.com/mishbahr/djangocms-forms/blob/master/djangocms_forms/templates/djangocms_forms/form_template/default.html

**Comment by mishbahr** [comment]
FYI If you just want to add CSS class "form-control" to all inputs, simply add the following to your project settings:

```python
DJANGOCMS_FORMS_WIDGET_CSS_CLASSES = {'__all__': ('form-control', ) }
```

or just to add it to "checkbox" widgets, add the following:

```python
DJANGOCMS_FORMS_WIDGET_CSS_CLASSES = {'checkbox': ('form-control', ) }
```

**Comment by binydev** [comment]
Oh, Thanks it works perfectly!
