### ISSUE TITLE
Dynamic DropDown

### ISSUE THREAD

**Issue by mykljohn** [mishbahr/djangocms-forms#58]
Hi, nice and easy, but I would like to use a dynamic dropdown list from one of my models (MySQL table)

I haven't been able to find any documentation on it for DjangoCMS so I figured I'd ask.  

Is this possible?

**Comment by mishbahr** [comment]
For the current implementation.. it's not possible to have model driven choice fields.

**Comment by mykljohn** [comment]
Bummer, Ok, I guess I'll have to use a text search.  This would be a nice addition.  Especially for drowndowns for Country or State, etc.
