### ISSUE TITLE
Feature Request - Add required to the input

### ISSUE THREAD

**Issue by leesolway** [mishbahr/djangocms-forms#6]
Would it be possible to add a required attribute to the actual input..

<input type="text" required>

**Comment by mishbahr** [comment]
Have a look at https://github.com/kmike/django-widget-tweaks. IMO this is beyond the current scope of the projec but I'll add it to my list of future enhancements.

**Comment by mishbahr** [comment]
Added logic for HTML5 required attributes  — See d5f1cbc193ed15bdd757d784bcff41e627f4d423
