### ISSUE TITLE
KeyError on 'current_page' in the form cleaned_data

### ISSUE THREAD

**Issue by marksweb** [mishbahr/djangocms-forms#8]
Where does `current_page` get set in the form?

I've had error reports come in that upon submission our dev site is returning a 500 error, and I'm seeing a KeyError on `current_page` from;
```python
else:
    messages.success(self.request,
        strip_tags(form.form_definition.post_submit_msg))
    return redirect(
        form.redirect_url or form.cleaned_data['current_page'])
```
I can only see attempts to get `current_page` from `cleaned_data`, but no other mention of it;
https://github.com/mishbahr/djangocms-forms/search?utf8=%E2%9C%93&q=current_page

I've debugged this & I can see what I expected - my form fields, plus `form_id` and `referrer`. Oddly this was working locally yesterday.

Should this not be doing `form.cleaned_data['referrer']` instead in order to return to the page you've posted from?

I'm running my forked codebase & it seems to work with this fix; https://github.com/mishbahr/djangocms-forms/compare/master...marksweb:referrer_fix

**Comment by mishbahr** [comment]
I'll look into this. Thanks for reporting.
