### ISSUE TITLE
Making successful submission a conversion point

### ISSUE THREAD

**Issue by zanderle** [mishbahr/djangocms-forms#9]
Hi!

I am trying to make my form be a conversion point on my website. Meaning, I would like to send some data to Google Analytics after the form was successfully submitted.  I have two questions about this:

1.) The sending to GA should be done, when formValid is called. What do you think would be the best way of going about this? Should I be extending the CMSForms in jquery.djangocms-forms.js, or is there a neater way of doing it?

2.) It'd be much easier if this was already a part of the project. I can create a PR for this feature, but am not sure if you would want to include it (I assume it would depend on whether or not this is a common requirement). Let me know if there is a need for this or not.

Thanks,
Žan

**Comment by mishbahr** [comment]
I'm already working on this feature.. I was planning on implementing it both client side .. so a onFormValid callback option for the jQuery plugin and also option to send data server side using Google measurment protocol.

Pull requests are welcome.. I can't guarantee to merge it in.. I will take your implentation into consideration.

Thank you.

Don't forget to 'Star' the repo... If you found it useful.

**Comment by mishbahr** [comment]
I'll close this (non-issue) —  I've added this to my long list todo things.
